/* confdefs.h */
#define PACKAGE_NAME "OpenVPN"
#define PACKAGE_TARNAME "openvpn"
#define PACKAGE_VERSION "2.6.1"
#define PACKAGE_STRING "OpenVPN 2.6.1"
#define PACKAGE_BUGREPORT "openvpn-users@lists.sourceforge.net"
#define PACKAGE_URL ""
#define OPENVPN_VERSION_RESOURCE 2,6,1,0
#define OPENVPN_VERSION_MAJOR 2
#define OPENVPN_VERSION_MINOR 6
#define OPENVPN_VERSION_PATCH ".1"
#define PACKAGE "openvpn"
#define VERSION "2.6.1"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define STDC_HEADERS 1
#define _ALL_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define __EXTENSIONS__ 1
#define TARGET_ALIAS "x86_64-apple-darwin22.1.0"
#define TARGET_DARWIN 1
#define TARGET_PREFIX "M"
#define IFCONFIG_PATH "/sbin/ifconfig"
#define IPROUTE_PATH ""
#define ROUTE_PATH "/sbin/route"
#define SYSTEMD_ASK_PASSWORD_PATH ""
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define RETSIGTYPE void
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define HAVE_FCNTL_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define HAVE_NETINET_IN_H 1
